# Generated by Django 5.2.5 on 2025-08-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('news_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('scrip_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('segment', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('dissem_dt_ist', models.DateTimeField(blank=True, null=True)),
                ('dissem_dt_utc', models.DateTimeField(blank=True, null=True)),
                ('received_dt_ist', models.DateTimeField(blank=True, null=True)),
                ('time_taken_sec', models.IntegerField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('pdf_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('xbrl_url', models.TextField(blank=True, null=True)),
                ('av_url', models.TextField(blank=True, null=True)),
                ('has_pdf', models.BooleanField(default=False)),
                ('has_xbrl', models.BooleanField(default=False)),
                ('has_av', models.BooleanField(default=False)),
                ('is_revision', models.BooleanField(default=False)),
                ('reg_tags', models.JSONField(blank=True, default=list)),
                ('company_url', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('page_no', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-dissem_dt_ist'],
            },
        ),
        migrations.CreateModel(
            name='PublicIssue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('security_name', models.CharField(max_length=512)),
                ('exchange_platform', models.CharField(blank=True, max_length=128, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('offer_price', models.CharField(blank=True, max_length=64, null=True)),
                ('face_value', models.CharField(blank=True, max_length=64, null=True)),
                ('type_of_issue', models.CharField(blank=True, max_length=64, null=True)),
                ('issue_status', models.CharField(blank=True, max_length=64, null=True)),
                ('price_min', models.FloatField(blank=True, null=True)),
                ('price_max', models.FloatField(blank=True, null=True)),
                ('type_of_issue_long', models.CharField(blank=True, max_length=128, null=True)),
                ('list_url', models.TextField(blank=True, null=True)),
                ('detail_url', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('pdf_links', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('file_urls', models.JSONField(blank=True, default=list)),
                ('uploaded_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'public_issues',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='public_issu_start_d_279b60_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('xbrl', 'XBRL'), ('audio_video', 'Audio/Video')], max_length=20)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mime', models.CharField(blank=True, max_length=120, null=True)),
                ('local_path', models.TextField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('r2_key', models.TextField(blank=True, null=True)),
                ('r2_url', models.TextField(blank=True, null=True)),
                ('bucket', models.TextField(blank=True, null=True)),
                ('text_excerpt', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scrape.announcement')),
            ],
            options={
                'db_table': 'announcement_attachments',
                'unique_together': {('announcement', 'url')},
            },
        ),
    ]
