# Generated by Django 5.2.5 on 2025-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeleniumAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_code', models.CharField(blank=True, max_length=20, null=True)),
                ('announcement_text', models.TextField(blank=True, null=True)),
                ('exchange_received_date', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_received_time', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_disseminated_date', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_disseminated_time', models.CharField(blank=True, max_length=20, null=True)),
                ('pdf_link_web', models.TextField(blank=True, null=True)),
                ('pdf_path_local', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'selenium_announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
