# Generated by Django 5.2.5 on 2025-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BseAnnouncementAggregate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bse_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('announcements_data', models.JSONField(blank=True, help_text='JSON array of all announcements for this company', null=True)),
                ('scrape_start_date', models.CharField(blank=True, help_text='Start date in DD-MM-YYYY format', max_length=20, null=True)),
                ('scrape_end_date', models.CharField(blank=True, help_text='End date in DD-MM-YYYY format', max_length=20, null=True)),
                ('pdfs_data', models.JSONField(blank=True, help_text='JSON array of PDF storage information', null=True)),
                ('total_announcements_count', models.IntegerField(default=0, help_text='Number of announcements in this record')),
                ('total_pdfs_count', models.IntegerField(default=0, help_text='Number of PDFs stored in cloud')),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bse_announcements_aggregate',
                'ordering': ['-last_scraped'],
                'indexes': [models.Index(fields=['bse_code'], name='bse_announc_bse_cod_c44c51_idx'), models.Index(fields=['company_name'], name='bse_announc_company_6db000_idx'), models.Index(fields=['last_scraped'], name='bse_announc_last_sc_e2f68d_idx'), models.Index(fields=['scrape_start_date', 'scrape_end_date'], name='bse_announc_scrape__992687_idx')],
                'constraints': [models.UniqueConstraint(fields=('bse_code', 'scrape_start_date', 'scrape_end_date'), name='uniq_bse_ann_code_dates')],
            },
        ),
        migrations.CreateModel(
            name='BseStockQuote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scripcode', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bse_stock_quotes',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['scripcode'], name='bse_stock_q_scripco_adbf59_idx'), models.Index(fields=['security_name'], name='bse_stock_q_securit_05827c_idx'), models.Index(fields=['basic_industry'], name='bse_stock_q_basic_i_797c5c_idx'), models.Index(fields=['scraped_at'], name='bse_stock_q_scraped_d63c0c_idx')],
                'constraints': [models.UniqueConstraint(fields=('scripcode',), name='uniq_bse_stock_scripcode')],
            },
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bse_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('security_name', models.CharField(blank=True, max_length=100, null=True)),
                ('actions_data', models.JSONField(blank=True, help_text='JSON array of all corporate actions for this company', null=True)),
                ('csv_r2_path', models.TextField(blank=True, help_text='R2 object key path', null=True)),
                ('csv_cloud_url', models.TextField(blank=True, help_text='R2 public URL for CSV file', null=True)),
                ('total_actions_count', models.IntegerField(default=0, help_text='Number of corporate actions in this record')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corporate_actions',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['bse_code'], name='corporate_a_bse_cod_9c1b24_idx'), models.Index(fields=['company_name'], name='corporate_a_company_ff2706_idx'), models.Index(fields=['last_updated'], name='corporate_a_last_up_c5fc1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('bse_code',), name='uniq_corp_action_bse_code')],
            },
        ),
        migrations.CreateModel(
            name='NseAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, help_text='Detailed announcement content', null=True)),
                ('exchange_received_date', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_received_time_only', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_disseminated_date', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_disseminated_time_only', models.CharField(blank=True, max_length=20, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=20, null=True)),
                ('attachment_size', models.CharField(blank=True, max_length=50, null=True)),
                ('attachment_link', models.TextField(blank=True, null=True)),
                ('xbrl_link', models.TextField(blank=True, null=True)),
                ('has_xbrl', models.BooleanField(default=False)),
                ('xbrl_nse_symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('xbrl_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('xbrl_subject', models.TextField(blank=True, null=True)),
                ('xbrl_description', models.TextField(blank=True, null=True)),
                ('xbrl_attachment_url', models.TextField(blank=True, null=True)),
                ('xbrl_datetime', models.CharField(blank=True, max_length=40, null=True)),
                ('xbrl_category', models.CharField(blank=True, max_length=120, null=True)),
                ('xbrl_parse_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nse_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'exchange_disseminated_time_only'], name='nse_announc_symbol_05e8f6_idx'), models.Index(fields=['xbrl_category'], name='nse_announc_xbrl_ca_f08164_idx'), models.Index(fields=['details'], name='idx_nse_ann_details'), models.Index(fields=['exchange_received_date'], name='idx_nse_ann_recv_date'), models.Index(fields=['exchange_disseminated_date'], name='idx_nse_ann_diss_date'), models.Index(fields=['symbol', 'exchange_disseminated_date'], name='idx_nse_ann_symbol_diss_date')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'subject', 'exchange_disseminated_time_only'), name='uniq_nse_ann_symbol_subject_time')],
            },
        ),
        migrations.CreateModel(
            name='NSECorporateAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, help_text='NSE stock symbol', max_length=50, unique=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name', max_length=255, null=True)),
                ('actions_data', models.JSONField(blank=True, help_text='JSON object with equity and sme corporate actions', null=True)),
                ('json_r2_path', models.TextField(blank=True, help_text='R2 object key path for JSON file', null=True)),
                ('json_cloud_url', models.TextField(blank=True, help_text='R2 public URL for JSON file', null=True)),
                ('total_actions_count', models.IntegerField(default=0, help_text='Total number of corporate actions (equity + sme)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nse_corporate_actions',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['symbol'], name='nse_corpora_symbol_0d9bce_idx'), models.Index(fields=['company_name'], name='nse_corpora_company_9c5b3a_idx'), models.Index(fields=['last_updated'], name='nse_corpora_last_up_eaa99b_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol',), name='uniq_nse_corp_action_symbol')],
            },
        ),
        migrations.CreateModel(
            name='NseStockQuote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nse_stock_quotes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol'], name='nse_stock_q_symbol_e5b09d_idx'), models.Index(fields=['company_name'], name='nse_stock_q_company_7744e8_idx'), models.Index(fields=['basic_industry'], name='nse_stock_q_basic_i_29877e_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol',), name='uniq_nse_stock_symbol')],
            },
        ),
        migrations.CreateModel(
            name='SeleniumAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_code', models.CharField(blank=True, max_length=20, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('announcement_text', models.TextField(blank=True, null=True)),
                ('exchange_received_date', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_received_time', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_disseminated_date', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_disseminated_time', models.CharField(blank=True, max_length=20, null=True)),
                ('pdf_link_web', models.TextField(blank=True, null=True)),
                ('pdf_path_local', models.TextField(blank=True, null=True)),
                ('pdf_path_cloud', models.TextField(blank=True, null=True)),
                ('pdf_r2_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'selenium_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_code', 'exchange_disseminated_date', 'exchange_disseminated_time'], name='selenium_an_company_84a525_idx'), models.Index(fields=['category'], name='selenium_an_categor_0e6755_idx')],
            },
        ),
    ]
