# Generated by Django 5.2.5 on 2025-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleniumannouncement',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='seleniumannouncement',
            index=models.Index(fields=['company_code', 'exchange_disseminated_date', 'exchange_disseminated_time'], name='selenium_an_company_84a525_idx'),
        ),
        migrations.AddIndex(
            model_name='seleniumannouncement',
            index=models.Index(fields=['category'], name='selenium_an_categor_0e6755_idx'),
        ),
    ]
