# Generated by Django 5.2.5 on 2025-09-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0002_remove_nseannouncement_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='nseannouncement',
            name='pdf_link_web',
            field=models.TextField(blank=True, help_text='Web URL for the PDF', null=True),
        ),
        migrations.AddField(
            model_name='nseannouncement',
            name='pdf_path_cloud',
            field=models.TextField(blank=True, help_text='R2 public URL for the PDF', null=True),
        ),
        migrations.AddField(
            model_name='nseannouncement',
            name='pdf_path_local',
            field=models.TextField(blank=True, help_text='Local file path for the PDF', null=True),
        ),
        migrations.AddField(
            model_name='nseannouncement',
            name='pdf_r2_path',
            field=models.TextField(blank=True, help_text='R2 object key for the PDF', null=True),
        ),
    ]
