# Generated by Django 5.2.5 on 2025-08-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0002_seleniumannouncement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NseAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('exchange_received_time', models.CharField(blank=True, max_length=40, null=True)),
                ('exchange_dissemination_time', models.CharField(blank=True, max_length=40, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=20, null=True)),
                ('attachment_size', models.CharField(blank=True, max_length=50, null=True)),
                ('attachment_link', models.TextField(blank=True, null=True)),
                ('xbrl_link', models.TextField(blank=True, null=True)),
                ('has_xbrl', models.BooleanField(default=False)),
                ('xbrl_nse_symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('xbrl_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('xbrl_subject', models.TextField(blank=True, null=True)),
                ('xbrl_description', models.TextField(blank=True, null=True)),
                ('xbrl_attachment_url', models.TextField(blank=True, null=True)),
                ('xbrl_datetime', models.CharField(blank=True, max_length=40, null=True)),
                ('xbrl_category', models.CharField(blank=True, max_length=120, null=True)),
                ('xbrl_parse_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nse_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'exchange_dissemination_time'], name='nse_announc_symbol_4dd90c_idx'), models.Index(fields=['xbrl_category'], name='nse_announc_xbrl_ca_f08164_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'subject', 'exchange_dissemination_time'), name='uniq_nse_ann_symbol_subject_time')],
            },
        ),
    ]
