# Generated by Django 5.2.5 on 2025-08-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0003_nseannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleniumannouncement',
            name='pdf_path_cloud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='pdf_r2_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
