# Generated by Django 5.2.5 on 2025-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0003_nseannouncement_pdf_link_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleniumannouncement',
            name='attachment_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='xbrl_attachment_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='xbrl_category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='xbrl_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='xbrl_datetime',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='xbrl_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='xbrl_nse_symbol',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='xbrl_parse_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seleniumannouncement',
            name='xbrl_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
