# Generated by Django 5.2.5 on 2025-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0004_seleniumannouncement_attachment_size_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seleniumannouncement',
            name='selenium_an_categor_0e6755_idx',
        ),
        migrations.AlterField(
            model_name='seleniumannouncement',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seleniumannouncement',
            name='headline',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='seleniumannouncement',
            index=models.Index(fields=['headline'], name='selenium_an_headlin_47d2cf_idx'),
        ),
    ]
