# Generated by Django 5.2.5 on 2025-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0004_seleniumannouncement_pdf_path_cloud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bse_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('security_name', models.CharField(blank=True, max_length=100, null=True)),
                ('actions_data', models.JSONField(blank=True, help_text='JSON array of all corporate actions for this company', null=True)),
                ('csv_r2_path', models.TextField(blank=True, help_text='R2 object key path', null=True)),
                ('csv_cloud_url', models.TextField(blank=True, help_text='R2 public URL for CSV file', null=True)),
                ('total_actions_count', models.IntegerField(default=0, help_text='Number of corporate actions in this record')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corporate_actions',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['bse_code'], name='corporate_a_bse_cod_9c1b24_idx'), models.Index(fields=['company_name'], name='corporate_a_company_ff2706_idx'), models.Index(fields=['last_updated'], name='corporate_a_last_up_c5fc1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('bse_code',), name='uniq_corp_action_bse_code')],
            },
        ),
    ]
