# Generated by Django 5.2.5 on 2025-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0005_remove_seleniumannouncement_selenium_an_categor_0e6755_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seleniumannouncement',
            name='selenium_an_headlin_47d2cf_idx',
        ),
        migrations.AlterField(
            model_name='seleniumannouncement',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
