# Generated by Django 5.2.5 on 2025-08-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0005_corporateaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BseStockQuote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scripcode', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bse_stock_quotes',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['scripcode'], name='bse_stock_q_scripco_adbf59_idx'), models.Index(fields=['security_name'], name='bse_stock_q_securit_05827c_idx'), models.Index(fields=['basic_industry'], name='bse_stock_q_basic_i_797c5c_idx'), models.Index(fields=['scraped_at'], name='bse_stock_q_scraped_d63c0c_idx')],
                'constraints': [models.UniqueConstraint(fields=('scripcode',), name='uniq_bse_stock_scripcode')],
            },
        ),
    ]
