# Generated by Django 5.2.5 on 2025-09-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0006_remove_seleniumannouncement_selenium_an_headlin_47d2cf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NseAnnouncementAggregate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nse_code', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('announcements_data', models.JSONField(blank=True, help_text='JSON array of all announcements for this company', null=True)),
                ('scrape_start_date', models.CharField(blank=True, help_text='Start date in DD-MM-YYYY format', max_length=20, null=True)),
                ('scrape_end_date', models.CharField(blank=True, help_text='End date in DD-MM-YYYY format', max_length=20, null=True)),
                ('pdfs_data', models.JSONField(blank=True, help_text='JSON array of PDF storage information', null=True)),
                ('total_announcements_count', models.IntegerField(default=0, help_text='Number of announcements in this record')),
                ('total_pdfs_count', models.IntegerField(default=0, help_text='Number of PDFs stored in cloud')),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nse_announcement_aggregate',
                'indexes': [models.Index(fields=['nse_code'], name='nse_announc_nse_cod_6c514b_idx')],
                'unique_together': {('nse_code', 'scrape_start_date', 'scrape_end_date')},
            },
        ),
    ]
