# Generated by Django 5.2.5 on 2025-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0006_bsestockquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsestockquote',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
