# Generated by Django 5.2.5 on 2025-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0007_nseannouncementaggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scraper_name', models.CharField(help_text="Name of the scraper (e.g., 'bse_announcements', 'nse_announcements')", max_length=50, unique=True)),
                ('is_first_run', models.BooleanField(default=True, help_text='True if this is the first time running the scraper')),
                ('last_scrape_date', models.CharField(blank=True, help_text='Last date scraped in DD-MM-YYYY format', max_length=20, null=True)),
                ('last_run_timestamp', models.DateTimeField(blank=True, help_text='When the scraper was last executed', null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this scraper is enabled')),
                ('scrape_interval_minutes', models.IntegerField(default=30, help_text='How often to run the scraper (in minutes)')),
                ('last_records_processed', models.IntegerField(default=0, help_text='Number of records processed in last run')),
                ('last_new_records', models.IntegerField(default=0, help_text='Number of new records added in last run')),
                ('last_error_message', models.TextField(blank=True, help_text='Last error message if any', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scraper_configurations',
                'ordering': ['scraper_name'],
            },
        ),
    ]
