# Generated by Django 5.2.5 on 2025-09-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0007_bsestockquote_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BseAnnouncementAggregate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bse_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('announcements_data', models.JSONField(blank=True, help_text='JSON array of all announcements for this company', null=True)),
                ('scrape_start_date', models.CharField(blank=True, help_text='Start date in DD-MM-YYYY format', max_length=20, null=True)),
                ('scrape_end_date', models.CharField(blank=True, help_text='End date in DD-MM-YYYY format', max_length=20, null=True)),
                ('pdfs_data', models.JSONField(blank=True, help_text='JSON array of PDF storage information', null=True)),
                ('total_announcements_count', models.IntegerField(default=0, help_text='Number of announcements in this record')),
                ('total_pdfs_count', models.IntegerField(default=0, help_text='Number of PDFs stored in cloud')),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bse_announcements_aggregate',
                'ordering': ['-last_scraped'],
                'indexes': [models.Index(fields=['bse_code'], name='bse_announc_bse_cod_c44c51_idx'), models.Index(fields=['company_name'], name='bse_announc_company_6db000_idx'), models.Index(fields=['last_scraped'], name='bse_announc_last_sc_e2f68d_idx'), models.Index(fields=['scrape_start_date', 'scrape_end_date'], name='bse_announc_scrape__992687_idx')],
                'constraints': [models.UniqueConstraint(fields=('bse_code', 'scrape_start_date', 'scrape_end_date'), name='uniq_bse_ann_code_dates')],
            },
        ),
    ]
