# Generated by Django 5.2.5 on 2025-09-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_scrape', '0008_bseannouncementaggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NseStockQuote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nse_stock_quotes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol'], name='nse_stock_q_symbol_e5b09d_idx'), models.Index(fields=['company_name'], name='nse_stock_q_company_7744e8_idx'), models.Index(fields=['basic_industry'], name='nse_stock_q_basic_i_29877e_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol',), name='uniq_nse_stock_symbol')],
            },
        ),
    ]
